[package]
name = "mats"
version = "2.0.0"
edition = "2024"
build = "build.rs"
license = "MIT OR Apache-2.0"

[dependencies]
glium = {version = "0.36.0", optional = true}

[features]
default = ["uniforms"]
uniforms = ["glium"]